-- MySQL Script generated by MySQL Workbench
-- Tuesday 23 January 2024 11:03:43 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MART
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MART
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MART` DEFAULT CHARACTER SET utf8 ;
USE `MART` ;

-- -----------------------------------------------------
-- Table `MART`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MART`.`seller` (
  `idseller` INT NOT NULL AUTO_INCREMENT,
  `seller_name` VARCHAR(100) NOT NULL,
  `seller_phone` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `country` VARCHAR(45) NOT NULL DEFAULT 'india',
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idseller`))
ENGINE = InnoDB
COMMENT = 'table where all the account information of a seller is present';


-- -----------------------------------------------------
-- Table `MART`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MART`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `idseller` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `subcategory` VARCHAR(45) NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `productImage` JSON NOT NULL,
  `priceUP` INT NOT NULL,
  `priceLOW` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NULL,
  `quantity` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `postTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idproduct`),

 
  CONSTRAINT `idseller`
    FOREIGN KEY (`idseller`)
    REFERENCES `MART`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
